import Footer from "./footer";
import "./globals.css";
import Navbar from "./navbar";

export const metadata = {
  title: "Blog test app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main>
          <Navbar></Navbar>
          <div className="min-h-screen bg-gray-900 flex items-center justify-center">
            <div className="bg-gray-800 shadow-xl rounded-lg p-6 w-full max-w-md">{children}</div>
          </div>
          <Footer></Footer>
        </main>
      </body>
    </html>
  );
}
